import React from 'react';
import { ArrowRight } from 'lucide-react';
import { curatedOutfits } from '../../data/mockData';

export default function CuratedOutfitsDesktop({ onSelectOutfit, onOpenLookbook }) {
  const [mainOutfit, middleTop, middleBottom, rightOutfit] = curatedOutfits;
  const card = (outfit, className, aspect = 'aspect-[3/4]') => <div onClick={() => onSelectOutfit(outfit)} className={`bg-white border border-[#E9E4DC] rounded-xl overflow-hidden group cursor-pointer hover:shadow-md transition-all flex flex-col justify-between ${className}`}><div className={`relative ${aspect} overflow-hidden bg-[#F4F1EA]`}><img src={outfit.image} alt={outfit.title} className="w-full h-full object-cover object-top group-hover:scale-103 transition-transform duration-500" /></div><div className="p-4 bg-white flex items-center justify-between"><h4 className="font-serif-luxury text-base font-bold text-[#151816]">{outfit.title}</h4><span className="px-2 py-0.5 text-[10px] font-semibold tracking-wider text-[#1C4A29] bg-[#ECF4EE] rounded-sm">{outfit.matchPercentage}% Match</span></div></div>;
  return <section className="py-10 border-b border-[#EAE6DF] bg-[#FBFBFA]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex flex-col sm:flex-row sm:items-end justify-between mb-7 gap-2"><div><h3 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-[#151816]">Curated Outfits</h3><p className="text-xs text-[#706D65] mt-1 font-normal">Expertly styled combinations based on your Style DNA.</p></div><button onClick={() => onOpenLookbook(mainOutfit)} className="group font-serif-luxury text-sm font-semibold text-[#1A3C24] flex items-center space-x-1.5"><span>View Lookbook</span><ArrowRight className="w-3.5 h-3.5" /></button></div><div className="grid grid-cols-1 md:grid-cols-12 gap-5 lg:gap-6">{card(mainOutfit, 'md:col-span-5 lg:col-span-4') }<div className="md:col-span-4 lg:col-span-4 flex flex-col gap-5">{card(middleTop, 'flex-1', 'aspect-[16/10]')}{card(middleBottom, 'flex-1', 'aspect-[16/10]')}</div>{card(rightOutfit, 'md:col-span-3 lg:col-span-4')}</div></div></section>;
}
