import React from 'react';
import { Share2, Heart, Plus, Sparkles, ChevronRight, Check } from 'lucide-react';
import { anchorItems } from '../../data/wardrobeFocusData';
import AddPieceModal from '../AddPieceModal';

export default function WardrobeFocusDesktop({ selectedItemId, isLiked, isAddOpen, toastMessage, onSelectItem, onAddOpen, onCloseAdd, onAddPiece, onShare, onToggleLike, onSelectOtherItem, onNavigateToCanvas }) {
  const item = anchorItems.find((entry) => entry.id === selectedItemId) || anchorItems[0];
  return <div className="bg-[#FBFBFA] min-h-screen text-[#151816] font-sans pb-16">
    {toastMessage && <div className="fixed top-20 right-6 z-50 bg-[#16291C] text-white px-4 py-2.5 rounded-lg shadow-xl text-xs flex items-center space-x-2 border border-[#2B4B34] animate-in fade-in"><Check className="w-4 h-4 text-emerald-400" /><span>{toastMessage}</span></div>}
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-8"><div className="mb-6"><h2 className="font-serif-luxury text-3xl font-bold tracking-wider text-[#151816] uppercase">DIGITAL WARDROBE</h2><div className="w-12 h-0.5 bg-[#183B22] mt-2" /></div><div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      <div className="lg:col-span-1 flex lg:flex-col gap-3 overflow-x-auto lg:overflow-visible pb-2 lg:pb-0">{anchorItems.map((entry) => <button key={entry.id} onClick={() => onSelectItem(entry.id)} className={`w-16 h-16 sm:w-20 sm:h-20 rounded-md overflow-hidden border-2 transition-all shrink-0 bg-white relative group ${selectedItemId === entry.id ? 'border-[#183B22] shadow-sm scale-102' : 'border-[#EAE6DF] hover:border-[#B5AEA1]'}`} title={entry.title}><img src={entry.thumbnail} alt={entry.title} className="w-full h-full object-cover" /></button>)}<button onClick={onAddOpen} className="w-16 h-16 sm:w-20 sm:h-20 rounded-md border-2 border-dashed border-[#CDC6B8] hover:border-[#183B22] flex items-center justify-center text-[#8C877B] bg-white" title="Thêm món đồ mới"><Plus className="w-6 h-6" /></button></div>
      <div className="lg:col-span-7 bg-white rounded-2xl border border-[#E8E3D8] overflow-hidden shadow-xs relative"><div className="absolute top-4 right-4 z-10"><span className="px-3 py-1 bg-[#F5F2EB] text-[#183B22] border border-[#DDD7CC] rounded-sm text-[10px] font-mono font-bold tracking-wider uppercase">ANCHOR ITEM</span></div><div className="w-full h-[520px] bg-[#F7F5F0] flex items-center justify-center p-8 overflow-hidden"><img src={item.image} alt={item.title} className="max-h-full max-w-full object-contain filter drop-shadow-md" /></div><div className="p-6 bg-white border-t border-[#EFECE6] flex items-end justify-between gap-4"><div><span className="text-xs font-mono text-[#8A867D] block mb-1">SKU: {item.sku}</span><h3 className="font-serif-luxury text-2xl font-bold text-[#151816] mb-3">{item.title}</h3><div className="flex flex-wrap gap-2">{item.badges.map((badge) => <span key={badge} className="px-3 py-1 rounded-sm bg-[#F2EFE8] text-xs font-mono font-bold text-[#4B4842]">{badge}</span>)}</div></div><div className="flex items-center space-x-2 shrink-0"><button onClick={onShare} className="w-10 h-10 rounded-md border border-[#DCD7CD] bg-white flex items-center justify-center text-[#55524B]" title="Chia sẻ trang phục"><Share2 className="w-4 h-4" /></button><button onClick={onToggleLike} className="w-10 h-10 rounded-md border border-[#DCD7CD] bg-white flex items-center justify-center" title="Lưu yêu thích"><Heart className={`w-4 h-4 ${isLiked ? 'fill-[#C53030] text-[#C53030]' : 'text-[#55524B]'}`} /></button></div></div></div>
      <div className="lg:col-span-4 bg-[#FBFBFA] border border-[#E8E3D8] rounded-2xl p-6 shadow-xs flex flex-col justify-between"><div className="space-y-6"><div className="flex items-center justify-between border-b border-[#EAE6DF] pb-4"><div className="flex items-center space-x-1.5"><h4 className="font-serif-luxury text-xl font-bold text-[#151816]">Suggestion</h4><Sparkles className="w-4 h-4 text-[#183B22]" /></div><span className="text-[10px] font-mono tracking-widest text-[#7C786F] uppercase font-bold">AI POWERED</span></div><div className="space-y-4">{item.suggestions.map((suggestion) => <div key={suggestion.id} className="p-3 bg-white rounded-xl border border-[#EAE6DF] flex items-center justify-between shadow-2xs"><div className="flex items-center space-x-3"><div className="w-14 h-14 rounded-md bg-[#F4F1EA] overflow-hidden shrink-0"><img src={suggestion.image} alt={suggestion.name} className="w-full h-full object-cover" /></div><div><h5 className="font-serif-luxury text-xs font-bold text-[#151816] line-clamp-1">{suggestion.name}</h5><span className="text-[10px] font-mono text-[#8C877C] block">{suggestion.brand}</span><div className="text-xs font-mono font-bold text-[#151816] mt-0.5">{suggestion.price}</div></div></div><span className="text-[11px] font-mono font-semibold text-[#183B22]">{suggestion.matchPercent}</span></div>)}</div><div className="space-y-2.5 pt-2"><button onClick={onSelectOtherItem} className="w-full py-3 rounded-md border border-[#DDD7CC] bg-white text-xs font-serif-luxury font-bold tracking-wider text-[#35322B] uppercase">ITEM OTHER</button><button onClick={onNavigateToCanvas} className="w-full py-3 rounded-md bg-[#183B22] text-white text-xs font-serif-luxury font-bold tracking-wider uppercase shadow-sm flex items-center justify-center space-x-2"><span>MIX CANVAS</span><ChevronRight className="w-4 h-4" /></button></div></div><p className="text-[10px] text-[#868278] italic text-center pt-6 mt-6 border-t border-[#EAE6DF]">&quot;These recommendations are based on your personal 'Minimalist Modern' style DNA and past interactions.&quot;</p></div>
    </div></div>
    <AddPieceModal isOpen={isAddOpen} onClose={onCloseAdd} onAddPiece={onAddPiece} />
  </div>;
}
